// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation}
 */
public final class PirInlineClassRepresentation extends
    org.jetbrains.kotlin.protobuf.GeneratedMessageLite implements
    // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation)
    PirInlineClassRepresentationOrBuilder {
  // Use PirInlineClassRepresentation.newBuilder() to construct.
  private PirInlineClassRepresentation(org.jetbrains.kotlin.protobuf.GeneratedMessageLite.Builder builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PirInlineClassRepresentation(boolean noInit) { this.unknownFields = org.jetbrains.kotlin.protobuf.ByteString.EMPTY;}

  private static final PirInlineClassRepresentation defaultInstance;
  public static PirInlineClassRepresentation getDefaultInstance() {
    return defaultInstance;
  }

  public PirInlineClassRepresentation getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final org.jetbrains.kotlin.protobuf.ByteString unknownFields;
  private PirInlineClassRepresentation(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    org.jetbrains.kotlin.protobuf.ByteString.Output unknownFieldsOutput =
        org.jetbrains.kotlin.protobuf.ByteString.newOutput();
    org.jetbrains.kotlin.protobuf.CodedOutputStream unknownFieldsCodedOutput =
        org.jetbrains.kotlin.protobuf.CodedOutputStream.newInstance(
            unknownFieldsOutput, 1);
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            underlyingPropertyName_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            underlyingPropertyType_ = input.readInt32();
            break;
          }
        }
      }
    } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      try {
        unknownFieldsCodedOutput.flush();
      } catch (java.io.IOException e) {
      // Should not happen
      } finally {
        unknownFields = unknownFieldsOutput.toByteString();
      }
      makeExtensionsImmutable();
    }
  }
  public static org.jetbrains.kotlin.protobuf.Parser<PirInlineClassRepresentation> PARSER =
      new org.jetbrains.kotlin.protobuf.AbstractParser<PirInlineClassRepresentation>() {
    public PirInlineClassRepresentation parsePartialFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
      return new PirInlineClassRepresentation(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public org.jetbrains.kotlin.protobuf.Parser<PirInlineClassRepresentation> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int UNDERLYING_PROPERTY_NAME_FIELD_NUMBER = 1;
  private int underlyingPropertyName_;
  /**
   * <code>required int32 underlying_property_name = 1;</code>
   */
  public boolean hasUnderlyingPropertyName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 underlying_property_name = 1;</code>
   */
  public int getUnderlyingPropertyName() {
    return underlyingPropertyName_;
  }

  public static final int UNDERLYING_PROPERTY_TYPE_FIELD_NUMBER = 2;
  private int underlyingPropertyType_;
  /**
   * <code>required int32 underlying_property_type = 2;</code>
   */
  public boolean hasUnderlyingPropertyType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 underlying_property_type = 2;</code>
   */
  public int getUnderlyingPropertyType() {
    return underlyingPropertyType_;
  }

  private void initFields() {
    underlyingPropertyName_ = 0;
    underlyingPropertyType_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUnderlyingPropertyName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasUnderlyingPropertyType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.jetbrains.kotlin.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, underlyingPropertyName_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, underlyingPropertyType_);
    }
    output.writeRawBytes(unknownFields);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt32Size(1, underlyingPropertyName_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt32Size(2, underlyingPropertyType_);
    }
    size += unknownFields.size();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(byte[] data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(
      byte[] data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseDelimitedFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  /**
   * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation}
   */
  public static final class Builder extends
      org.jetbrains.kotlin.protobuf.GeneratedMessageLite.Builder<
        org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation)
      org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentationOrBuilder {
    // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      underlyingPropertyName_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      underlyingPropertyType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation getDefaultInstanceForType() {
      return org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation.getDefaultInstance();
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation build() {
      org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation buildPartial() {
      org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation result = new org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.underlyingPropertyName_ = underlyingPropertyName_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.underlyingPropertyType_ = underlyingPropertyType_;
      result.bitField0_ = to_bitField0_;
      return result;
    }

    public Builder mergeFrom(org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation other) {
      if (other == org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation.getDefaultInstance()) return this;
      if (other.hasUnderlyingPropertyName()) {
        setUnderlyingPropertyName(other.getUnderlyingPropertyName());
      }
      if (other.hasUnderlyingPropertyType()) {
        setUnderlyingPropertyType(other.getUnderlyingPropertyType());
      }
      setUnknownFields(
          getUnknownFields().concat(other.unknownFields));
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUnderlyingPropertyName()) {
        
        return false;
      }
      if (!hasUnderlyingPropertyType()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int underlyingPropertyName_ ;
    /**
     * <code>required int32 underlying_property_name = 1;</code>
     */
    public boolean hasUnderlyingPropertyName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 underlying_property_name = 1;</code>
     */
    public int getUnderlyingPropertyName() {
      return underlyingPropertyName_;
    }
    /**
     * <code>required int32 underlying_property_name = 1;</code>
     */
    public Builder setUnderlyingPropertyName(int value) {
      bitField0_ |= 0x00000001;
      underlyingPropertyName_ = value;
      
      return this;
    }
    /**
     * <code>required int32 underlying_property_name = 1;</code>
     */
    public Builder clearUnderlyingPropertyName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      underlyingPropertyName_ = 0;
      
      return this;
    }

    private int underlyingPropertyType_ ;
    /**
     * <code>required int32 underlying_property_type = 2;</code>
     */
    public boolean hasUnderlyingPropertyType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 underlying_property_type = 2;</code>
     */
    public int getUnderlyingPropertyType() {
      return underlyingPropertyType_;
    }
    /**
     * <code>required int32 underlying_property_type = 2;</code>
     */
    public Builder setUnderlyingPropertyType(int value) {
      bitField0_ |= 0x00000002;
      underlyingPropertyType_ = value;
      
      return this;
    }
    /**
     * <code>required int32 underlying_property_type = 2;</code>
     */
    public Builder clearUnderlyingPropertyType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      underlyingPropertyType_ = 0;
      
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation)
  }

  static {
    defaultInstance = new PirInlineClassRepresentation(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.PirInlineClassRepresentation)
}